name: content_nation
description: "Content Nation - AI-Powered Content Discovery Platform - Personalized content discovery across YouTube, Spotify, and TMDB"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # HTTP & API
  http: ^1.2.1
  dio: ^5.9.0
  
  # Authentication
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # YouTube Integration (Web compatible)
  # youtube_player_flutter: ^9.0.1  # Not web compatible
  
  # Spotify Integration (Web compatible)
  # spotify_sdk: ^3.0.2  # Not web compatible
  
  # Image & Media (Web compatible)
  # image_picker: ^1.0.7  # Not web compatible
  # photo_view: ^0.14.0  # Not web compatible
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  # path_provider: ^2.1.3  # Not needed for web
  equatable: ^2.0.5
  url_launcher: ^6.2.5
  
  # AI & ML (Web compatible)
  # tflite_flutter: ^0.10.4  # Not web compatible
  
  # AI & ML Libraries
  collection: ^1.18.0
  math_expressions: ^2.6.0
  vector_math: ^2.1.4
  
  # Animations
  lottie: ^3.1.2
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/models/
