// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHGl5TIrV8tSzoYd4QkDODPKqEe6bI3oM',
    appId: '1:113881222128:web:cff5b77c7ebabd929eab35',
    messagingSenderId: '113881222128',
    projectId: 'content-nation-e0549',
    authDomain: 'content-nation-e0549.firebaseapp.com',
    storageBucket: 'content-nation-e0549.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHGl5TIrV8tSzoYd4QkDODPKqEe6bI3oM',
    appId: '1:113881222128:android:cff5b77c7ebabd929eab35',
    messagingSenderId: '113881222128',
    projectId: 'content-nation-e0549',
    storageBucket: 'content-nation-e0549.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHGl5TIrV8tSzoYd4QkDODPKqEe6bI3oM',
    appId: '1:113881222128:ios:cff5b77c7ebabd929eab35',
    messagingSenderId: '113881222128',
    projectId: 'content-nation-e0549',
    storageBucket: 'content-nation-e0549.firebasestorage.app',
    iosBundleId: 'com.example.aiBasedContentRecommendationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHGl5TIrV8tSzoYd4QkDODPKqEe6bI3oM',
    appId: '1:113881222128:ios:cff5b77c7ebabd929eab35',
    messagingSenderId: '113881222128',
    projectId: 'content-nation-e0549',
    storageBucket: 'content-nation-e0549.firebasestorage.app',
    iosBundleId: 'com.example.aiBasedContentRecommendationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHGl5TIrV8tSzoYd4QkDODPKqEe6bI3oM',
    appId: '1:113881222128:web:cff5b77c7ebabd929eab35',
    messagingSenderId: '113881222128',
    projectId: 'content-nation-e0549',
    authDomain: 'content-nation-e0549.firebaseapp.com',
    storageBucket: 'content-nation-e0549.firebasestorage.app',
  );
}
